- name: backend server
  hosts: backend
  become: yes
  task:
  - name: disable node
    ansible.builtin.command: dnf module disable nodejs -y

  - name: disable node
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node 
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create dir
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download file of backend
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app

  - name: Force Install "coffee-script" node.js package.
    community.general.npm:
      name: npm
      state: present
  

  


  