- name: backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable node
    ansible.builtin.command: dnf module disable nodejs -y

  - name: disable node
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node 
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create user
    ansible.builtin.user:
      name: expense

  - name: create dir
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download file of backend
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: npm Install node.js package.
    community.general.npm:
      path: /app
  
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: demon reload
    ansible.builtin.systemd_service:
      name: backend
      daemon_reload: true
      state: restarted
      enabled: true

  - name: mysql install
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: ExpenseApp@1
      target: /app/schema/backend.sql

  - name: Install MySQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    # - cryptography
    - PyMySQL  

  


  