- name: mysql server
  hosts: mysql
  become: yes
  tasks: 
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start mysql server
    ansible.builtin.service:
      name: mysql-server
      state: restarted
      enabled: yes

     
